# Generated by Django 5.0.3 on 2024-06-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_cartitem_cart_items_orderitem_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
